apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        giantswarm.io/service-type: "{{ .Values.serviceType }}"
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      tolerations:
      - effect: NoSchedule
        operator: "Exists"
        key: node-role.kubernetes.io/master
      nodeSelector:
        kubernetes.io/role: master
      priorityClassName: giantswarm-critical
      containers:
        - image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          name: {{ .Values.name }}
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --cloud-provider={{ .Values.configmap.provider }}
            - --expander={{ .Values.configmap.expander }}
            - --logtostderr=true
            - --stderrthreshold=info
            {{- if eq .Values.configmap.provider "aws" }}
            - --node-group-auto-discovery=asg:tag={{ tpl (join "," .Values.configmap.autoDiscovery.tags) . }}
            {{- end }}
            {{- range $key, $value := .Values.configmap.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}

          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
