apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "{{ .Values.serviceType }}"
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        giantswarm.io/service-type: "{{ .Values.serviceType }}"
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      tolerations:
      - effect: NoSchedule
        operator: "Exists"
        key: node-role.kubernetes.io/master
      nodeSelector:
        kubernetes.io/role: master
      priorityClassName: giantswarm-critical
      containers:
        - image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          name: {{ .Values.name }}
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --cloud-provider={{ .Values.provider }}
            - --logtostderr=true
            - --stderrthreshold=info
            {{- if eq .Values.provider "azure" }}
            {{- if .Values.autoscalingGroups }}
            {{- range .Values.autoscalingGroups }}
            - --nodes={{ printf "%s:%s:%s-%s" .minSize .maxSize $.Values.clusterID "worker" }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.provider "aws" }}
            - --node-group-auto-discovery=asg:tag={{ tpl (join "," .Values.autoDiscovery.tags) . }}
            {{- end }}
            {{- range $key, $value := .Values.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}

          env:
            {{- if eq .Values.provider "azure" }}
            - name: ARM_SUBSCRIPTION_ID
              value: {{ .Values.subscriptionID }}
            - name: ARM_RESOURCE_GROUP
              value: {{ .Values.clusterID }}
            - name: ARM_USE_MANAGED_IDENTITY_EXTENSION
              value: {{ quote .Values.managedIdentity }}
            - name: ARM_VM_TYPE
              value: {{ .Values.azureVMType }}
            {{- end }}

          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-certificates.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
