kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: TCP
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress

