apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    # kubernetes.io/cluster-service are kept to be displayed in kubectl cluster-info
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: {{ .Values.name }}
    giantswarm.io/monitoring: "true"
  annotations:
    giantswarm.io/monitoring-path: /metrics
    giantswarm.io/monitoring-port: "8085"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
spec:
  selector:
    {{- include "labels.selector" . | nindent 4 }}
  ports:
  - name: "metrics"
    port: 8085
    protocol: TCP
