apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "cluster-autoscaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cluster-autoscaler.fullname" . }}
  resourcePolicy:
    containerPolicies:
    - containerName: cluster-autoscaler
      controlledValues: RequestsAndLimits
      mode: Auto
      minAllowed:
        {{- toYaml .Values.autoscaling.minAllowed | nindent 8 }}
  updatePolicy:
    updateMode: Auto
