apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cluster-autoscaler.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.name }}
      controlledValues: RequestsAndLimits
      mode: Auto
      minAllowed:
        {{- toYaml .Values.autoscaling.minAllowed | nindent 8 }}
  updatePolicy:
    updateMode: Auto
