{{ if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.name }} 
  namespace: {{ .Values.namespace }} 
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.name }}
      controlledValues: RequestsAndLimits
      mode: Auto
      minAllowed:
        cpu: {{ .Values.vpa.minAllowed.cpu }}
        memory: {{ .Values.vpa.minAllowed.memory }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ .Values.name }}
  updatePolicy:
    updateMode: Auto
{{ end }}
