name: cluster-autoscaler
namespace: kube-system
serviceType: managed

userID: 65534
groupID: 65534

port: 8085

# Make sure to update the docs at https://github.com/giantswarm/docs/blob/master/src/layouts/shortcodes/autoscaler_utilization_threshold.html if you change the defaults below
image:
  registry: quay.io
  name: giantswarm/cluster-autoscaler
  tag: v1.15.2

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: "test-cluster"
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: "aws"
# azure contains the configuration values required by the azure provider and can be overridden
# with custom values
azure:
  # Azure subscription where the VMSS are created
  subscriptionID: "changeme"
  # Whether or not to use the credentials automatically provisioned on the VMSS instances
  managedIdentity: true
  # Type of deployment used on Azure
  vmType: VMSS

# Command line arguments passed to the cluster-autoscaler process
extraArgs:
  scan-interval: 10s
  scale-down-utilization-threshold: 0.65
  skip-nodes-with-system-pods: true
  skip-nodes-with-local-storage: false
  expander: least-waste

