name: cluster-autoscaler
namespace: kube-system
serviceType: managed

userID: 65534
groupID: 65534

port: 8085

# Make sure to update the docs at https://github.com/giantswarm/docs/blob/master/src/layouts/shortcodes/autoscaler_utilization_threshold.html if you change the defaults below
configmap:
  expander: least-waste
  scanInterval: 30s
  scaleDownUnneededTime: 5m0s
  scaleDownUtilizationThreshold: 0.5
  skipNodesWithLocalStorage: "false"
  skipNodesWithSystemPods: "true"
  balanceSimilarNodeGroups: "true"
  newPodScaleUpDelay: 0s

isManagementCluster: false
managementCluster:
  name: ""

image:
  registry: docker.io
  name: giantswarm/cluster-autoscaler
  tag: v1.25.1

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: "test-cluster"
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: "aws"
# azure contains the configuration values required by the azure provider and can be overridden
# with custom values
azure:
  # Azure subscription where the VMSS are created
  subscriptionID: ""
  # Whether or not to use the credentials automatically provisioned on the VMSS instances
  managedIdentity: true
  # Type of deployment used on Azure
  vmType: VMSS

clusterAutoscalerResources:
  limits:
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 400Mi

verticalPodAutoscaler:
  minAllowed:
    cpu: 200m
    memory: 400Mi

registry:
  domain: docker.io

balancingIgnoreLabels:
  balancing-ignore-label_1: ip
  balancing-ignore-label_2: vpc.amazonaws.com/eniConfig
  balancing-ignore-label_3: giantswarm.io/machine-deployment
